# compose.yml
version: "3.9"

services:
  db:
      platform: linux/arm64/v8
      image: postgres
      volumes:
      - ./data/db:/var/lib/postgresql/data
      environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
      platform: linux/arm64/v8
      build: .
      command: python manage.py runserver 0.0.0.0:${PORT:-8000}
      volumes:
      - .:/app
      ports:
      - ${PORT:-8000}:${PORT:-8000}
      environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      depends_on:
      - db
